# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!


tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  generate:
    cmds:
      - wire .\\cmd
    silent: true

  build:
    cmds:
      - go build -o .\\tmp\\main.exe .\\cmd
    silent: true

  run:
    cmds:
      - .\\tmp\\main.exe -conf .\\config\\config.toml
    silent: true
