// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"mvp/config"
	"mvp/internal/data"
	"mvp/internal/handler"
	"mvp/internal/server"
	"mvp/utils/app"
	"mvp/utils/log"
)

// Injectors from wire.go:

// initApp 初始化应用
func initApp(log2 log.Logger, conf *config.Config) (*app.App, func(), error) {
	db := data.NewDB(conf, log2)
	dataData := data.NewData(db, log2)
	userRepo := data.NewUserRepo(dataData, log2)
	userHandler := handler.NewUserHandler(userRepo, log2)
	httpServer := server.NewHTTPServer(userHandler, conf)
	appApp := newApp(log2, conf, httpServer)
	return appApp, func() {
	}, nil
}
